### ISSUE TITLE
Tab focus doesn't return to slides button when ESCaping from slides popup

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella-slide-plugins#6]
Issue: 
When clicking ESC key from the slides popup, the focus should return to the slides control button. This is the behavior of all the other Paella control bar buttons. But the focus is unknown after clicking ESC from the slides popup.

Steps:
1. Go to https://paellaplayer.upv.es/player.html?id=belmar-multiresolution-remote
2. Tab to the "Show Slides" slide button in the control bar
3. Click "Enter" key to open the slides popup
4. Press "ESC" key to exit the slides popup
EXPECTED: the tab focus returns to the "Show Slides" button, as before clicking open the slides popup
ACTUAL: The tab focus is unknown. Clicking "Enter" key has no effect. But clicking "Tab" key does highlight the next control bar button.

**Comment by ferserc1** [comment]
Fixed in version 1.48.1. You can test it in [paella player](https://paellaplayer.upv.es) website
