### ISSUE TITLE
Reduce height of progress bar slide marks

### ISSUE THREAD

**Issue by owi92** [polimediaupv/paella-slide-plugins#8]
Following the discussion in https://github.com/polimediaupv/paella-skins/issues/6 where I mistakenly brought up this issue: it would be great if the slide marks could be reduced in size to fit the progress bar, like in the following screenshot (stolen from [this comment](https://github.com/polimediaupv/paella-skins/issues/6#issuecomment-2225875721)):
<img width="802" alt="Bildschirmfoto 2024-07-16 um 11 39 04" src="https://github.com/user-attachments/assets/eee8e938-8529-409b-81dc-a95fa5b1c343">

**Comment by miesgre** [comment]
Commit dd0a749b395c1060193715b7ab9a1f46aaf7ac26 makes it.  [paella-slide-plugins@1.48.2](https://github.com/polimediaupv/paella-slide-plugins/releases/tag/1.48.2)
